-- SUPERSEDED -- do not apply this file by hand.
--
-- The schema now lives in database/migrations/, applied by a runner that records
-- what it has already run:
--
--   createdb language_learning
--   npm run migrate:dev          # local (ts-node)
--   npm run build && npm run migrate   # server (compiled)
--
-- Why this file is no longer the source of truth: it used CREATE TABLE IF NOT
-- EXISTS throughout, so re-running it against a database whose tables already
-- existed in an older shape silently did nothing. That is exactly what happened
-- to lesson_responses -- the live table kept a `question_answers` column long
-- after the code moved to `mcq_answers` + `short_answer_responses`, and every
-- lesson submission failed with a 500. See
-- database/migrations/002_split_question_answers.sql.
--
-- For the current full schema, read database/migrations/001_baseline.sql, then
-- each numbered migration after it in order.
